version: 2.1

orbs:
  golang: cci-orb/golang@volatile

defaults: &defaults
  executor: golang/buster
  environment:
    GO111MODULE: 'on'
  working_directory: /go/src/github.com/zchee/color

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - golang/gomod
      - run:
          name: Install go-junit-report binary
          command: |
            GO111MODULE=off go get -u github.com/jstemmer/go-junit-report
      - run:
          name: Take test coverage and output test results to junit syntax
          command: |
            mkdir -p /tmp/ci/artifacts /tmp/ci/test-results
            go test -v -race -covermode=atomic -coverpkg=./... -coverprofile=/tmp/ci/artifacts/coverage.out ./... 2>&1 | tee /dev/stderr | go-junit-report -set-exit-code > /tmp/ci/test-results/junit.xml
            if [[ -f '/tmp/ci/artifacts/coverage.out' ]]; then go tool cover -html=/tmp/ci/artifacts/coverage.out -o /tmp/ci/artifacts/coverage.html; fi
      - run:
          name: Upload test coverages to codecov.io
          command: |
            bash <(curl -s https://codecov.io/bash) -f /tmp/ci/artifacts/coverage.out
      - store_artifacts:
          path: /tmp/ci/artifacts
      - store_artifacts:
          path: /tmp/ci/test-results
      - store_test_results:
          path: /tmp/ci/test-results

  bench:
    docker:
      - image: google/cloud-sdk:slim
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /etc/google/application_default_credentials.json
    working_directory: /go/src/github.com/zchee/color
    steps:
      - checkout
      - run:
          name: Authorize GCP project
          command: |
            mkdir -p $(dirname ${GOOGLE_APPLICATION_CREDENTIALS})
            echo "${GOOGLE_APPLICATION_CREDENTIALS_JSON}" > ${GOOGLE_APPLICATION_CREDENTIALS}
            gcloud auth activate-service-account --key-file ${GOOGLE_APPLICATION_CREDENTIALS}
            gcloud config set project ${GOOGLE_CLOUD_PROJECT}
      - run:
          name: Install make
          command: |
            apt-get update
            apt-get install -yqq --no-install-recommends --no-install-suggests make
      - run:
          name: Run benchmark on GCE
          command: |
            make bench/gce

workflows:
  version: 2
  workflows:
    jobs:
      - test:
          context: org-global
      - bench:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          context: org-global
