version: 2.1

orbs:
  executor: cci-orb/golang@dev:master-5c90288

defaults: &defaults
  executor: executor/stretch
  environment:
    GO111MODULE: 'on'
  working_directory: /go/src/github.com/zchee/color

commands:
  gomod:
    steps:
      - restore_cache:
          keys:
            - go-mod-v0-{{ checksum "go.sum" }}
      - run:
          name: Download go module dependencies and fetch to vender directory
          command: |
            go mod download
            go mod vendor -v
      - save_cache:
          key: go-mod-v0-{{ checksum "go.sum" }}
          paths:
            - '/go/pkg/mod'
            - '/go/src/github.com/zchee/color/vendor'

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - gomod
      - run:
          name: Take test coverage and output test results to junit syntax
          command: |
            mkdir -p test-results
            go test -v -race -covermode=atomic -coverpkg=./... -coverprofile=coverage.out $(go list -f='{{if or .TestGoFiles .XTestGoFiles}}{{.ImportPath}}{{end}}' ./...) 2>&1 | tee /dev/stderr | go-junit-report -set-exit-code > test-results/report.xml
      - run:
          name: Upload test coverages to codecov.io
          command: |
            bash <(curl -s https://codecov.io/bash) -Z -f coverage.out
      - store_test_results:
          path: test-results

workflows:
  version: 2
  workflows:
    jobs:
      - test:
          context: org-global
